RealisticVision:
  motion_module:
    # - "models/Motion_Module/mm_sd_v14.ckpt"
    - "/mnt/petrelfs/sichenyang.p/code/diffsuion/git_code/AnimateDiff/AnimateDiff/models/Motion_Module/mm_sd_v14.ckpt"

  # dreambooth_path: "models/DreamBooth_LoRA/realisticVisionV20_v20.safetensors"
  dreambooth_path: "/mnt/petrelfs/sichenyang.p/code/diffsuion/git_code/AnimateDiff/AnimateDiff/models/DreamBooth_LoRA/realisticVisionV20_v20.safetensors"
  lora_model_path: ""

  seed:           [502, 5206]
  steps:          25
  guidance_scale: 7.5

  # filter_params:
  #   method: 'butterworth'
  #   n: 4
  #   d_s: 0.25
  #   d_t: 0.25

  filter_params:
    method: 'gaussian'
    d_s: 0.25
    d_t: 0.25

  prompt:
    - "A cute raccoon playing guitar in a boat on the ocean."
    - "A panda standing on a surfboard in the ocean in sunset."

  n_prompt:
    - ""
    - ""

